--- # Configuration
g: 1
dT: 0.2
bodies:
  - pos: {x:   0., y: 0.}
    mass: 100.
    mom: {x:   0., y: 0.}
  - pos: {x: 100., y: 0.}
    mass: 0.1
    mom: {x:   0., y: 1.}
  - pos: {x: 200., y: 0.}
    mass: 0.1
    mom: {x:   0., y: 0.7}
  - pos: {x: 300., y: 0.}
    mass: 0.1
    mom: {x:   0., y: 0.5}
