--- # Configuration
# debug: true                # debug enabled
g: 1                       # universal gravitational constant
dT: 0.5                    # time interval of the simulation
bodies:                    # list of bodies
  - pos: {x:   0., y: 0.}  # position
    mass: 100.             # mass
    mom: {x:   0., y: 0.}  # momentum (speed)
  - pos: {x: 100., y: 0.}
    mass: 0.1
    mom: {x:   0., y: 1.}
  - pos: {x: 200., y: 0.}
    mass: 0.1
    mom: {x:   0., y: 0.7}
  - pos: {x: 300., y: 0.}
    mass: 0.1
    mom: {x:   0., y: 0.5}
  - pos: {x: 150., y: 0.}
    mass: 0.1
    mom: {x:   0., y: 0.8}
